### ISSUE TITLE
Is this package still maintained ?

### ISSUE THREAD

**Issue by agilare** [yohang/CalendR#51]
There is no commit for 1.5 year and the last answer to an issue was 2 years ago.

**Comment by mpdude** [comment]
*metoo*

@yohang Could you please be so kind to let us know if you're still maintaining this?

Personally, I don't expect you to reply to or analyze bug reports or even fix the issues reported. 

Yet, it would be helpful to know whether you will be able to review and/or merge pull requests in a timely manner (say, two or three weeks?). If *yes*, then we know it's worthwhile looking into the come and suggesting fixes. If *no*, we know it's time to fork and carry on ourselves.

🍻

**Comment by yohang** [comment]
Hi,

I didn't abandon this library but don't expect to much work on it before the end of the year.

My work takes me a lot of time, and don't allow me to do anything in open-source. I'm working on a solution but it'll take some time ;)
